- name: Install ALL prerequisites
  apt:
    name:
      - default-jre
      - apt-transport-https
      - curl
      - software-properties-common
    state: present
  become: yes

- name: Add Elasticsearch APT Repository Key
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
  become: yes

- name: Add Elasticsearch APT repository
  apt_repository:
    repo: "deb https://artifacts.elastic.co/packages/7.x/apt stable main"
    state: present
  become: yes

- name: Install Elasticsearch fot Ubuntu
  apt:
    name: elasticsearch
    state: present
  become: yes

- name: Enable and start Elasticsearch service
  systemd:
    name: elasticsearch
    enabled: yes
    state: started
  become: yes

- name: Install Kibana for Ubuntu
  apt:
    name: kibana
    state: present
  become: yes

- name: Enable and start Kibana Service
  systemd:
    name: kibana
    enabled: yes
    state: started
  become: yes

- name: Install Logstash for Ubuntu
  apt:
    name: logstash
    state: present
  become: yes

- name: Enable and start Logstash Service
  systemd:
    name: logstash
    enabled: yes
    state: started
  become: yes
      
- name: Restart Elasticsearch and Kibana
  systemd:
    name: "{{ item }}"
    state: restarted
  loop:
    - elasticsearch
    - kibana
